dist: xenial
language: cpp
compiler: clang
install:
  - pip install --user conan
  - conan user
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
- curl -f -T IpFilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhankhenshaw:$BINTRAY_API_KEY "https://api.bintray.com/content/hankhenshaw/MidRep/MiddlePack/$TRAVIS_BUILD_NUMBER/IpFilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"